services:
  streamlit:
    build:
      context: .
      args:
        GITHUB_URL: ${GITHUB_URL}
    container_name: streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - streamlit_data:/app
    restart: always
volumes:
  streamlit_data: